namespace CTrader.Services.Analysis;

public static class TickerNames
{
    private static readonly Dictionary<string, string> Names = new(StringComparer.OrdinalIgnoreCase)
    {
        // Mega-Cap Tech
        ["AAPL"] = "Apple",
        ["MSFT"] = "Microsoft",
        ["GOOGL"] = "Alphabet (Google)",
        ["GOOG"] = "Alphabet (Google)",
        ["AMZN"] = "Amazon",
        ["META"] = "Meta Platforms",
        ["NVDA"] = "NVIDIA",
        ["TSLA"] = "Tesla",
        ["TSM"] = "Taiwan Semiconductor",
        ["AVGO"] = "Broadcom",
        ["ORCL"] = "Oracle",
        ["ADBE"] = "Adobe",
        ["CRM"] = "Salesforce",
        ["CSCO"] = "Cisco Systems",
        ["ACN"] = "Accenture",
        ["IBM"] = "IBM",
        ["INTC"] = "Intel",
        ["AMD"] = "AMD",
        ["QCOM"] = "Qualcomm",
        ["TXN"] = "Texas Instruments",
        ["NOW"] = "ServiceNow",
        ["INTU"] = "Intuit",
        ["AMAT"] = "Applied Materials",
        ["MU"] = "Micron Technology",
        ["LRCX"] = "Lam Research",
        ["KLAC"] = "KLA Corporation",
        ["SNPS"] = "Synopsys",
        ["CDNS"] = "Cadence Design",
        ["MRVL"] = "Marvell Technology",
        ["PLTR"] = "Palantir Technologies",
        ["SNOW"] = "Snowflake",
        ["NET"] = "Cloudflare",
        ["CRWD"] = "CrowdStrike",
        ["PANW"] = "Palo Alto Networks",
        // Finance
        ["JPM"] = "JPMorgan Chase",
        ["V"] = "Visa",
        ["MA"] = "Mastercard",
        ["BAC"] = "Bank of America",
        ["WFC"] = "Wells Fargo",
        ["GS"] = "Goldman Sachs",
        ["MS"] = "Morgan Stanley",
        ["BLK"] = "BlackRock",
        ["C"] = "Citigroup",
        ["AXP"] = "American Express",
        ["SCHW"] = "Charles Schwab",
        ["PYPL"] = "PayPal",
        ["SQ"] = "Block (Square)",
        ["COIN"] = "Coinbase",
        // Healthcare
        ["UNH"] = "UnitedHealth Group",
        ["JNJ"] = "Johnson & Johnson",
        ["LLY"] = "Eli Lilly",
        ["PFE"] = "Pfizer",
        ["ABBV"] = "AbbVie",
        ["MRK"] = "Merck",
        ["TMO"] = "Thermo Fisher",
        ["ABT"] = "Abbott Laboratories",
        ["BMY"] = "Bristol-Myers Squibb",
        ["AMGN"] = "Amgen",
        ["GILD"] = "Gilead Sciences",
        ["MRNA"] = "Moderna",
        ["NVO"] = "Novo Nordisk",
        // Consumer / Retail
        ["WMT"] = "Walmart",
        ["PG"] = "Procter & Gamble",
        ["KO"] = "Coca-Cola",
        ["PEP"] = "PepsiCo",
        ["COST"] = "Costco",
        ["HD"] = "Home Depot",
        ["MCD"] = "McDonald's",
        ["NKE"] = "Nike",
        ["SBUX"] = "Starbucks",
        ["DIS"] = "Walt Disney",
        ["NFLX"] = "Netflix",
        ["ABNB"] = "Airbnb",
        ["BKNG"] = "Booking Holdings",
        // Energy / Industrials
        ["XOM"] = "ExxonMobil",
        ["CVX"] = "Chevron",
        ["COP"] = "ConocoPhillips",
        ["BA"] = "Boeing",
        ["CAT"] = "Caterpillar",
        ["GE"] = "GE Aerospace",
        ["UPS"] = "UPS",
        ["RTX"] = "RTX (Raytheon)",
        ["LMT"] = "Lockheed Martin",
        ["DE"] = "Deere & Company",
        // ETFs / Indices
        ["SPY"] = "S&P 500 ETF",
        ["QQQ"] = "Nasdaq-100 ETF",
        ["IWM"] = "Russell 2000 ETF",
        ["DIA"] = "Dow Jones ETF",
        ["VIX"] = "CBOE Volatility Index",
    };

    public static string? GetName(string symbol)
    {
        return Names.TryGetValue(symbol, out var name) ? name : null;
    }
}
