// <auto-generated />
using System;
using CTrader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTrader.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CTrader.Data.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Level");

                    b.HasIndex("Timestamp");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("CTrader.Data.Entities.NewsArticle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SentimentScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbols")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("CTrader.Data.Entities.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Key")
                        .IsUnique();

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Trading",
                            DataType = "decimal",
                            Description = "Maximum position size in USD",
                            Key = "MaxPositionSize",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3724),
                            Value = "10000"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Trading",
                            DataType = "int",
                            Description = "Maximum number of open positions",
                            Key = "MaxOpenPositions",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3730),
                            Value = "5"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Trading",
                            DataType = "bool",
                            Description = "Enable/disable trading",
                            Key = "TradingEnabled",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3731),
                            Value = "false"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Risk",
                            DataType = "decimal",
                            Description = "Maximum portfolio risk (2%)",
                            Key = "MaxPortfolioRisk",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3733),
                            Value = "0.02"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Risk",
                            DataType = "decimal",
                            Description = "Default stop loss percentage (5%)",
                            Key = "StopLossPercent",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3734),
                            Value = "0.05"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Risk",
                            DataType = "decimal",
                            Description = "Default take profit percentage (10%)",
                            Key = "TakeProfitPercent",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3737),
                            Value = "0.10"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Strategy",
                            DataType = "json",
                            Description = "Preferred market regimes for trading",
                            Key = "PreferredRegimes",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3738),
                            Value = "[\"RiskOn\",\"Neutral\"]"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Strategy",
                            DataType = "int",
                            Description = "Analysis interval in minutes",
                            Key = "AnalysisInterval",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3739),
                            Value = "60"
                        },
                        new
                        {
                            Id = 9,
                            Category = "LLM",
                            DataType = "string",
                            Description = "LLM provider (Anthropic/OpenAI)",
                            Key = "Provider",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3740),
                            Value = "Anthropic"
                        },
                        new
                        {
                            Id = 10,
                            Category = "LLM",
                            DataType = "string",
                            Description = "LLM model to use",
                            Key = "Model",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3742),
                            Value = "claude-sonnet-4-20250514"
                        },
                        new
                        {
                            Id = 11,
                            Category = "LLM",
                            DataType = "int",
                            Description = "Maximum tokens for LLM response",
                            Key = "MaxTokens",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3743),
                            Value = "4096"
                        },
                        new
                        {
                            Id = 12,
                            Category = "News",
                            DataType = "int",
                            Description = "News fetch interval in minutes",
                            Key = "FetchIntervalMinutes",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3744),
                            Value = "15"
                        },
                        new
                        {
                            Id = 13,
                            Category = "News",
                            DataType = "int",
                            Description = "Maximum articles per fetch",
                            Key = "MaxArticlesPerFetch",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3745),
                            Value = "50"
                        },
                        new
                        {
                            Id = 14,
                            Category = "News",
                            DataType = "json",
                            Description = "Enabled news sources",
                            Key = "EnabledSources",
                            UpdatedAt = new DateTime(2026, 6, 7, 20, 21, 48, 803, DateTimeKind.Utc).AddTicks(3747),
                            Value = "[\"Finnhub\",\"AlphaVantage\",\"RSS\"]"
                        });
                });

            modelBuilder.Entity("CTrader.Data.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Strategy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("CTrader.Data.Entities.RegimeAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Reasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedStrategy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegimeAnalyses");
                });

            modelBuilder.Entity("CTrader.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Commission")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Regime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Strategy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
